### ISSUE TITLE
Handling security-related bugs

### ISSUE THREAD

**Issue by wibeasley** [aldefouw/redcap_cypress#28]
If a test uncovers a security vulnerability, it shouldn't be available to the public.  Maybe we see if vandy would fund a private instance of circle ci (or whatever could be web-scraped/mined but a malicious user looking to exploit a system with phi).

**Comment by aldefouw** [comment]
Hi @wibeasley .  Thanks for the comments.  

Sorry that it has taken me so long to get back to this, but I wanted to mull this over a bit and think about whether this should be a concern or not.

After some careful consideration, I think there are a few items worth note here:

**1. Specific Goals and Scope of the Tests**

First off, I completely agree that security vulnerabilities (and bugs) are a real problem and security is definitely paramount to data integrity.  Thus, we should all be very keen on protecting our data in REDCap, and if we spot something we need to report it to Vanderbilt.

While I definitely can appreciate the mindset behind your concern, on the other hand, I think it's important to consider the goals and scope of Core Validation Test Scripts as defined by the Regulatory and Software Committee.

Quite frankly - the key is that they're _validation test scripts_.  The reason that's key is because the committee has set out to validate that features in REDCap are working as advertised.  

The test scripts are NOT specifically written as destructive tests that are exercising things in the hopes that things will break or we'll be able to break-in to things.

The tests don't aim to find security vulnerabilities or bugs, and that holds true for the core tests as well.  This is one of the reasons why helper methods are provided to login to the system.  We aren't looking for authentication vulnerabilities.  That's simply outside the scope of what we're trying to do.

_2. How Tests are Written_

Core tests are developed by humans in the Regulatory & Software Validation committee who've identified the feature as a core feature.  

Because they are developed by human beings, they are written in a specific way to test a particular feature of REDCap.  

While it's possible that could draw out a bug or security vulnerability in the process, the test scripts are manually exercised by a human before they are written into an automated test here.

Because they are manually exercised first, the due diligence is on the human who writes the test to report a security vulnerability or bug to Vanderbilt.  All we are doing is translating the spec.

Thus, we should never see reports of bugs or security problems in this issue section of the repository.

_3. Cypress isn't a good tool for vulnerability testing _

There are better tools specifically designed to test vulnerabilities than Cypress.

Working through the web browser itself is generally not the best way to find holes.

---

All that said, I'm not going to say that a private instance of CircleCI would be a bad idea.  If Vandy wants to fund something because they are concerned about the risk, more power to them.

I just think that the risk of an unreported security vulnerability being uncovered by one of these automated validation tests is extremely low because that isn't the focus.

I'm also not sure how it would be unveiling anything secret considering there's a long-standing change log of security vulnerabilities listed for the public to view right here:
https://www.cvedetails.com/vulnerability-list/vendor_id-12719/product_id-25239/Project-redcap-Redcap.html

That isn't the be-all end-all list - I'm aware of other issues beyond this.  My overall point is that our goal isn't to find bugs.  Our goal is provide a validation of the core features so that when auditors come around, we have some proof that REDCap actually does what it claims to.

**Comment by wibeasley** [comment]
@aldefouw, Cool.  Good points.  I'm convinced and am closing the issue.  At your next committee meeting, consider  
* presenting these parameters & risks.  
* proposing that if someone does write a test that potentially exposes a security flaw, flag it somehow so it will NOT run on a public CircleCI instance.

**Comment by aldefouw** [comment]
Great points, Will.

I'm glad that you brought this up because it's something we can write into the process.
